const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const D=window.GreenXData;let demoSession=false;
function imgSrc(v){if(!v)return '../assets/solar.svg';return v.startsWith('assets/')?'../'+v:v}let currentEntity=null;let cache={projects:[],services:[],products:[],clients:[],settings:null,inquiries:[]};
function alertMsg(msg,type='good'){const el=$('#globalAlert');el.innerHTML=`<div class="alert ${type}">${esc(msg)}</div>`;setTimeout(()=>el.innerHTML='',4500)}
function slugify(s=''){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
function showAdmin(){ $('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden'); const p=$('#modePill');if(!D.isConnected()){p.textContent='Demo Mode';p.classList.add('demo')} }
async function start(){if(D.isConnected()){const s=await D.session();if(s){showAdmin();await refreshAll()}}}
$('#demoBtn').onclick=async()=>{demoSession=true;showAdmin();await refreshAll()};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const a=$('#loginAlert');try{await D.signIn(fd.get('email'),fd.get('password'));showAdmin();await refreshAll()}catch(err){a.innerHTML=`<div class="alert warn">${esc(err.message||'Sign in failed')}</div>`}};
$('#logoutBtn').onclick=async()=>{await D.signOut();location.reload()};
$$('.side-nav button').forEach(b=>b.onclick=()=>{ $$('.side-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#panel-'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent=b.textContent.trim();if(b.dataset.tab==='enquiries')loadInquiries() });
async function refreshAll(){try{const [projects,services,products,clients,settings]=await Promise.all([D.adminGet('projects'),D.adminGet('services'),D.adminGet('products'),D.adminGet('clients'),D.getSettings()]);cache={...cache,projects,services,products,clients,settings};renderAll();fillSettings();await loadInquiries()}catch(e){alertMsg(e.message||'Could not load admin data','warn');console.error(e)}}
function status(p){return p.published!==false?'<span class="badge">Published</span>':'<span class="badge draft">Draft</span>'}
function actions(table,id){return `<div class="actions"><button class="btn btn-light" data-edit="${table}" data-id="${esc(id)}">Edit</button><button class="btn btn-danger" data-delete="${table}" data-id="${esc(id)}">Delete</button></div>`}
function renderAll(){
 $('#statProjects').textContent=cache.projects.length;$('#statServices').textContent=cache.services.length;$('#statClients').textContent=cache.clients.length;
 $('#projectsBody').innerHTML=cache.projects.length?cache.projects.map(p=>`<tr><td><img class="thumb" src="${esc(imgSrc(p.cover_image))}"></td><td><strong>${esc(p.title)}</strong><br><span class="hint">${esc(p.client_name||'')}</span></td><td>${esc(p.category||'')}</td><td>${esc(p.location||'')}</td><td>${status(p)}</td><td>${actions('projects',p.id)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No projects yet.</div></td></tr>';
 $('#servicesBody').innerHTML=cache.services.length?cache.services.map(p=>`<tr><td style="font-size:1.5rem">${esc(p.icon||'✦')}</td><td><strong>${esc(p.title)}</strong></td><td>${esc(p.short_description||'')}</td><td>${status(p)}</td><td>${actions('services',p.id)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No services yet.</div></td></tr>';
 $('#productsBody').innerHTML=cache.products.length?cache.products.map(p=>`<tr><td><img class="thumb" src="${esc(imgSrc(p.image_url))}"></td><td><strong>${esc(p.title)}</strong></td><td>${esc(p.category||'')}</td><td>${status(p)}</td><td>${actions('products',p.id)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No products yet.</div></td></tr>';
 $('#clientsBody').innerHTML=cache.clients.length?cache.clients.map(p=>`<tr><td>${p.logo_url?`<img class="thumb" style="object-fit:contain" src="${esc(imgSrc(p.logo_url))}">`:'—'}</td><td><strong>${esc(p.name)}</strong></td><td>${p.website_url?`<a href="${esc(p.website_url)}" target="_blank">Open ↗</a>`:'—'}</td><td>${status(p)}</td><td>${actions('clients',p.id)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No clients yet.</div></td></tr>';
 $$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit,b.dataset.id));$$('[data-delete]').forEach(b=>b.onclick=()=>removeEntity(b.dataset.delete,b.dataset.id));
}
function field(name,label,value='',type='text',full=false,extra=''){const cls=full?'field full':'field';if(type==='textarea')return `<div class="${cls}"><label>${label}</label><textarea name="${name}" ${extra}>${esc(value)}</textarea></div>`;if(type==='checkbox')return `<div class="${cls}"><label><input type="checkbox" name="${name}" ${value?'checked':''}> ${label}</label></div>`;return `<div class="${cls}"><label>${label}</label><input type="${type}" name="${name}" value="${esc(value)}" ${extra}></div>`}
function uploadField(name,label,current=''){return `<div class="field full"><label>${label}</label>${current?`<img class="image-preview" src="${esc(imgSrc(current))}" alt="Preview"><div class="hint">Current file: ${esc(current)}</div>`:''}<input type="file" name="${name}_file" accept="image/*,.gif,.svg"><div class="hint">JPG, PNG, WebP, SVG and animated GIF supported. You can also paste a direct URL below.</div><input name="${name}" value="${esc(current)}" placeholder="Image URL"></div>`}
function editorMarkup(table,row={}){
 if(table==='projects') return field('title','Project Title',row.title,'text',true,'required')+field('category','Category',row.category)+field('client_name','Client Name',row.client_name)+field('location','Location',row.location)+field('capacity','Capacity / Technical Scope',row.capacity)+field('completion_date','Completion Date',row.completion_date,'date')+field('short_description','Short Description',row.short_description,'textarea',true)+field('full_description','Full Project Description',row.full_description,'textarea',true)+field('services_provided','Services Provided',row.services_provided,'textarea',true)+uploadField('cover_image','Cover Image / GIF',row.cover_image)+`<div class="field full"><label>Add Project Gallery Images / GIFs</label><input type="file" name="_gallery_files" accept="image/*,.gif,.svg" multiple><div class="hint">Select multiple files. Existing gallery images are kept.</div><textarea name="_gallery_urls" placeholder="Optional: paste one direct image/GIF URL per line"></textarea></div>`+field('featured','Featured Project',row.featured,'checkbox')+field('published','Published',row.published!==false,'checkbox');
 if(table==='services') return field('title','Service / Solution Name',row.title,'text',true,'required')+field('icon','Small Icon / Emoji',row.icon)+field('sort_order','Display Order',row.sort_order||1,'number')+field('link_url','Click Link (optional)',row.link_url)+field('short_description','Short Description',row.short_description,'textarea',true)+field('details','Details',row.details,'textarea',true)+uploadField('image_url','Service Icon / Image / GIF',row.image_url)+field('published','Published',row.published!==false,'checkbox');
 if(table==='products') return field('title','Product Name',row.title,'text',true,'required')+field('category','Category',row.category)+field('short_description','Short Description',row.short_description,'textarea',true)+uploadField('image_url','Product Image / GIF',row.image_url)+field('published','Published',row.published!==false,'checkbox');
 if(table==='clients') return field('name','Client / Partner Name',row.name,'text',true,'required')+field('website_url','Website Link (optional)',row.website_url)+field('sort_order','Display Order',row.sort_order||1,'number')+uploadField('logo_url','Client Logo / GIF',row.logo_url)+field('published','Published',row.published!==false,'checkbox');
}
function openEditor(table,id=null){const row=id?(cache[table].find(x=>String(x.id)===String(id))||{}):{};currentEntity={table,id};$('#modalTitle').textContent=(id?'Edit ':'Add ')+table.slice(0,-1).replace(/^./,c=>c.toUpperCase());$('#entityForm').innerHTML=editorMarkup(table,row)+`<div class="form-actions"><button class="btn btn-light" type="button" id="cancelEdit">Cancel</button><button class="btn btn-dark" type="submit">Save</button></div>`;$('#editModal').classList.add('open');$('#cancelEdit').onclick=closeModal}
function closeModal(){ $('#editModal').classList.remove('open'); currentEntity=null }$('#closeModal').onclick=closeModal;$('#editModal').onclick=e=>{if(e.target.id==='editModal')closeModal()};
$('#addProjectBtn').onclick=()=>openEditor('projects');$('#addServiceBtn').onclick=()=>openEditor('services');$('#addProductBtn').onclick=()=>openEditor('products');$('#addClientBtn').onclick=()=>openEditor('clients');
$('#entityForm').onsubmit=async e=>{e.preventDefault();if(!currentEntity)return;const {table,id}=currentEntity;const fd=new FormData(e.currentTarget);const row=id?{id}:{};for(const [k,v] of fd.entries()){if(k.endsWith('_file')||k.startsWith('_'))continue;row[k]=v}for(const cb of e.currentTarget.querySelectorAll('input[type=checkbox]'))row[cb.name]=cb.checked;if(row.title&&!row.slug)row.slug=slugify(row.title);for(const name of ['cover_image','image_url','logo_url']){const file=fd.get(name+'_file');if(file&&file.size){try{row[name]=await D.uploadFile(file,table)}catch(err){alertMsg('Image upload failed: '+err.message,'warn');return}}}try{const saved=await D.adminSave(table,row);if(table==='projects'){const urls=(fd.get('_gallery_urls')||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);for(const file of fd.getAll('_gallery_files')){if(file&&file.size)urls.push(await D.uploadFile(file,'projects/gallery'))}if(urls.length)await D.adminAddProjectImages(saved.id,urls)}closeModal();await refreshAll();alertMsg('Saved successfully.')}catch(err){alertMsg(err.message||'Could not save','warn')}};
async function removeEntity(table,id){if(!confirm('Delete this item? This cannot be undone.'))return;try{await D.adminDelete(table,id);await refreshAll();alertMsg('Deleted.')}catch(err){alertMsg(err.message||'Delete failed','warn')}}
function fillSettings(){const f=$('#settingsForm'),s=cache.settings||{};Object.entries(s).forEach(([k,v])=>{const e=f.elements[k];if(e&&typeof v!=='object')e.value=v??''})}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const row={};for(const [k,v] of fd.entries()){if(k!=='logoFile'&&k!=='heroFile')row[k]=v}try{const lf=$('#logoFile').files[0],hf=$('#heroFile').files[0];if(lf)row.logo_url=await D.uploadFile(lf,'branding');if(hf)row.hero_image=await D.uploadFile(hf,'branding');cache.settings=await D.saveSettings(row);fillSettings();alertMsg('Website content updated.')}catch(err){alertMsg(err.message||'Could not save settings','warn')}};
async function loadInquiries(){try{cache.inquiries=await D.getInquiries();$('#statEnquiries').textContent=cache.inquiries.filter(x=>(x.status||'New')==='New').length;$('#enquiriesBody').innerHTML=cache.inquiries.length?cache.inquiries.map(i=>`<tr><td>${i.created_at?new Date(i.created_at).toLocaleString():'—'}</td><td><strong>${esc(i.name)}</strong><br><span class="hint">${esc(i.company||'')} ${esc(i.phone||'')} ${esc(i.email||'')}</span></td><td>${esc(i.service||'')}</td><td style="max-width:360px">${esc(i.message||'')}<br><span class="hint">${esc(i.location||'')}</span></td><td><select data-inquiry="${esc(i.id)}"><option ${i.status==='New'?'selected':''}>New</option><option ${i.status==='Contacted'?'selected':''}>Contacted</option><option ${i.status==='Quotation Sent'?'selected':''}>Quotation Sent</option><option ${i.status==='Closed'?'selected':''}>Closed</option></select></td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No enquiries yet.</div></td></tr>';$$('[data-inquiry]').forEach(s=>s.onchange=async()=>{await D.updateInquiry(s.dataset.inquiry,s.value);await loadInquiries()})}catch(err){console.error(err)}}
$('#refreshEnquiries').onclick=loadInquiries;start().catch(console.error);
