import Image from 'next/image'; import Link from 'next/link'; import SectionTitle from '@/components/SectionTitle'; import { CategoryCard, ProductCard, ProjectCard, ServiceCard } from '@/components/Cards'; import QuoteForm from '@/components/QuoteForm'; import { getClients,getProducts,getProjects,getServices,getSettings } from '@/lib/data'; import { PRODUCT_CATEGORY_META } from '@/lib/catalog';
export default async function Home(){ const [settings,services,projects,products,clients]=await Promise.all([getSettings(),getServices(),getProjects(),getProducts(),getClients()]); const featuredProjects=projects.filter(p=>p.featured).slice(0,3); const featuredProducts=products.filter(p=>p.featured).slice(0,4); return <>
<section className="hero"><div className="hero-grid-bg"/><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow light">POWER • ENERGY • INFRASTRUCTURE</span><h1>{settings.hero_title}</h1><p>{settings.hero_subtitle}</p><div className="hero-actions"><Link className="btn btn-primary" href="/contact#quote">Start a Project</Link><Link className="btn btn-ghost" href="/projects">View Portfolio</Link></div><div className="hero-trust"><span><b>01</b> Consultation</span><span><b>02</b> Engineering</span><span><b>03</b> Installation</span><span><b>04</b> Support</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><Image src={settings.hero_image_url||'/assets/hero-engineering.svg'} alt="Green X engineering solutions" fill priority sizes="(max-width:900px) 100vw, 48vw"/><div className="floating-card fc-one"><strong>End-to-end execution</strong><span>Survey → Design → Commissioning</span></div><div className="floating-card fc-two"><strong>Bangladesh focused</strong><span>Commercial • Industrial • Residential</span></div></div></div></section>
<section className="trust-strip"><div className="container trust-grid"><div><b>Solar</b><span>Rooftop & hybrid</span></div><div><b>Power</b><span>Generator & UPS</span></div><div><b>Vertical Mobility</b><span>Lift & elevator</span></div><div><b>Lifecycle Support</b><span>Maintenance & AMC</span></div></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="What we do" title="Engineering systems that keep businesses moving." body="One team for power, renewable energy, vertical transportation and long-term support."/><div className="service-grid">{services.slice(0,6).map((s,i)=><ServiceCard key={s.slug} item={{...s,display_order:i+1}}/>)}</div></div></section>
<section className="section dark-section"><div className="container split-feature"><div><span className="eyebrow light">Solar & Energy Storage</span><h2>Turn unused rooftop space into a working energy asset.</h2><p>Green X can support site survey, system sizing, equipment selection, installation, testing and maintenance for rooftop, hybrid and off-grid solar applications.</p><ul className="check-list"><li>Commercial rooftop solar</li><li>Hybrid solar + battery backup</li><li>Solar generator integration</li><li>Operations & maintenance</li></ul><Link className="btn btn-primary" href="/solutions/solar-energy">Explore Solar Solutions</Link></div><div className="feature-visual"><Image src="/assets/solar-project.svg" alt="Solar engineering" fill sizes="50vw"/></div></div></section>
<section className="section"><div className="container"><div className="title-row"><SectionTitle eyebrow="Project portfolio" title="A better way to present completed work." body="The preview items below show the final case-study style. Replace sample entries from Admin with Green X projects."/><Link href="/projects" className="text-link">View all projects →</Link></div><div className="project-grid">{featuredProjects.map(p=><ProjectCard key={p.slug} item={p}/>)}</div></div></section>
<section className="section soft-section"><div className="container"><div className="title-row"><SectionTitle eyebrow="Product catalog" title="Products organized around the way clients buy." body="Browse dedicated category pages, then open any product for specifications and enquiry."/><Link href="/products" className="text-link">Browse complete catalog →</Link></div><div className="home-category-strip">{PRODUCT_CATEGORY_META.slice(0,4).map(c=><CategoryCard key={c.slug} item={c} href={`/products/category/${c.slug}`} count={products.filter(p=>p.category===c.name).length}/>)}</div><div className="home-featured-products"><span className="eyebrow">Featured equipment</span><div className="product-grid">{featuredProducts.map(p=><ProductCard key={p.slug} item={p}/>)}</div></div></div></section>
<section className="section"><div className="container process-wrap"><SectionTitle eyebrow="How we work" title="From first survey to long-term support." center/><div className="process-grid">{['Consultation','Site Survey','Design & Proposal','Supply & Installation','Testing & Commissioning','Maintenance'].map((x,i)=><div key={x} className="process-item"><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3><p>{['Understand your requirement and operating priorities.','Review site conditions, load and practical constraints.','Prepare technical scope, equipment and commercial proposal.','Execute with planned delivery, safety and coordination.','Verify operation, handover and documentation.','Keep the system dependable with scheduled support.'][i]}</p></div>)}</div></div></section>
<section className="section dark-section"><div className="container"><SectionTitle eyebrow="Who we serve" title="Built for Bangladesh businesses and infrastructure." body="Use the Clients section in Admin to replace these audience placeholders with your approved customer logos."/><div className="client-grid">{clients.map(c=><div className="client-logo" key={c.name}>{c.logo_url?<Image src={c.logo_url} alt={c.name} width={160} height={64}/>:<span>{c.name}</span>}</div>)}</div></div></section>
<section id="quote" className="section quote-section"><div className="container quote-layout"><div><span className="eyebrow">Start a project</span><h2>Tell us what you need. We’ll help define the right engineering scope.</h2><p>Solar, generator, lift, electrical work or maintenance—send the requirement and your team can follow up from the Admin enquiry inbox.</p></div><QuoteForm/></div></section>
</> }
