'use client';
import { useEffect,useState } from 'react';

type Field={name:string;label:string;type?:'text'|'textarea'|'checkbox'|'date'|'number'|'json'|'image'|'select';options?:string[];placeholder?:string};
const configs:Record<string,{title:string;fields:Field[]}>={
projects:{title:'Projects',fields:[{name:'title',label:'Project title'},{name:'slug',label:'URL slug'},{name:'category',label:'Category',type:'select',options:['Solar Energy','Generator & Backup Power','Lift & Elevator','Electrical Engineering','Lightning Protection','Maintenance & Support']},{name:'client_name',label:'Client name'},{name:'location',label:'Location'},{name:'capacity',label:'Capacity / scope'},{name:'completion_date',label:'Completion date',type:'date'},{name:'short_description',label:'Short description',type:'textarea'},{name:'description',label:'Full description',type:'textarea'},{name:'cover_image_url',label:'Cover image',type:'image'},{name:'services_provided',label:'Services provided (JSON array)',type:'json',placeholder:'["Design","Supply","Installation"]'},{name:'technical_details',label:'Technical details (JSON object)',type:'json',placeholder:'{"Capacity":"250 kWp"}'},{name:'featured',label:'Featured on homepage',type:'checkbox'},{name:'published',label:'Published',type:'checkbox'},{name:'display_order',label:'Display order',type:'number'}]},
products:{title:'Products',fields:[{name:'name',label:'Product name'},{name:'slug',label:'URL slug'},{name:'category',label:'Category',type:'select',options:['Solar Generators','Solar Panels','Inverters','Battery & Storage','Generators','Lift & Elevator','UPS & Power Backup']},{name:'brand',label:'Brand'},{name:'short_description',label:'Short description',type:'textarea'},{name:'description',label:'Full description',type:'textarea'},{name:'image_url',label:'Product image',type:'image'},{name:'brochure_url',label:'Brochure URL'},{name:'specifications',label:'Specifications (JSON object)',type:'json',placeholder:'{"Power":"500W","Battery":"512Wh"}'},{name:'featured',label:'Featured on homepage',type:'checkbox'},{name:'published',label:'Published',type:'checkbox'},{name:'display_order',label:'Display order',type:'number'}]},
services:{title:'Services',fields:[{name:'title',label:'Service title'},{name:'slug',label:'URL slug'},{name:'short_description',label:'Short description',type:'textarea'},{name:'description',label:'Full description',type:'textarea'},{name:'image_url',label:'Image / GIF',type:'image'},{name:'features',label:'Features (JSON array)',type:'json',placeholder:'["Survey","Design","Installation"]'},{name:'featured',label:'Featured',type:'checkbox'},{name:'published',label:'Published',type:'checkbox'},{name:'display_order',label:'Display order',type:'number'}]},
clients:{title:'Clients & Partners',fields:[{name:'name',label:'Client / partner name'},{name:'logo_url',label:'Logo / GIF',type:'image'},{name:'website_url',label:'Clickable website URL'},{name:'published',label:'Published',type:'checkbox'},{name:'display_order',label:'Display order',type:'number'}]}
};
function slugify(x:string){return x.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
export default function AdminResourceManager({resource}:{resource:'projects'|'products'|'services'|'clients'}){const cfg=configs[resource];const [items,setItems]=useState<any[]>([]);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<any>(null);const [form,setForm]=useState<any>({published:true,featured:false,display_order:0});const [message,setMessage]=useState('');const [uploading,setUploading]=useState('');const [media,setMedia]=useState<any[]>([]);
async function load(){const r=await fetch(`/api/admin/${resource}`,{cache:'no-store'});if(r.ok)setItems(await r.json())}useEffect(()=>{load()},[resource]);
async function start(item?:any){setEditing(item||null);setForm(item?{...item}:{published:true,featured:false,display_order:items.length+1});setOpen(true);setMessage('');setMedia([]);if(resource==='projects'&&item?.id){const r=await fetch('/api/admin/project_media',{cache:'no-store'});if(r.ok){const all=await r.json();setMedia(all.filter((m:any)=>m.project_id===item.id));}}}
function change(name:string,value:any){setForm((f:any)=>({...f,[name]:value,...((name==='title'||name==='name')&&!f.slug?{slug:slugify(value)}:{})}))}
async function upload(field:string,file?:File){if(!file)return;setUploading(field);const fd=new FormData();fd.append('file',file);fd.append('folder',resource);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const data=await r.json();if(r.ok)change(field,data.url);else setMessage(data.error||'Upload failed');setUploading('')}
async function save(){setMessage('Saving…');const body:any={...form};try{for(const f of cfg.fields.filter(f=>f.type==='json')){if(typeof body[f.name]==='string')body[f.name]=JSON.parse(body[f.name]|| (f.placeholder?.startsWith('[')?'[]':'{}'));}delete body.created_at;delete body.updated_at;delete body.demo;const method=editing?'PATCH':'POST';if(editing)body.id=editing.id;const r=await fetch(`/api/admin/${resource}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){setMessage(data.error||'Save failed');return}setEditing(data);setForm(data);await load();setMessage(resource==='projects'&&!editing?'Project saved. You can now add gallery images below.':'Saved. Public website data is updated.');if(resource!=='projects')setOpen(false);}catch{setMessage('Please check JSON fields. Use valid JSON arrays/objects.');}
}
async function addGallery(file?:File){if(!file||!editing?.id)return;setUploading('gallery');const fd=new FormData();fd.append('file',file);fd.append('folder','projects/gallery');const up=await fetch('/api/admin/upload',{method:'POST',body:fd});const ud=await up.json();if(!up.ok){setMessage(ud.error||'Upload failed');setUploading('');return;}const r=await fetch('/api/admin/project_media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:editing.id,media_url:ud.url,media_type:ud.resource_type==='video'?'video':'image',display_order:media.length+1})});const d=await r.json();if(r.ok)setMedia(m=>[...m,d]);else setMessage(d.error||'Could not save gallery image');setUploading('');}
async function removeMedia(id:string){await fetch('/api/admin/project_media',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});setMedia(m=>m.filter(x=>x.id!==id));}
async function remove(id:string){if(!confirm('Delete this item?'))return;await fetch(`/api/admin/${resource}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load()}
return <div className="admin-page"><div className="admin-heading"><div><span className="eyebrow">Content</span><h1>{cfg.title}</h1><p>Manage what appears on the public website.</p></div><button className="btn btn-primary" onClick={()=>start()}>+ Add new</button></div>{message&&<div className="admin-message">{message}</div>}<div className="admin-table">{items.map(item=><div className="admin-row" key={item.id}><div className="row-main"><b>{item.title||item.name}</b><span>{item.category||item.location||item.website_url||item.slug}</span></div><span className={`state ${item.published?'live':'draft'}`}>{item.published?'Published':'Draft'}</span><button onClick={()=>start(item)}>Edit</button><button className="danger" onClick={()=>remove(item.id)}>Delete</button></div>)}{!items.length&&<div className="empty-state"><h3>No records yet.</h3><p>The public site is currently using polished sample content. Add your first real item here.</p></div>}</div>
{open&&<div className="drawer-backdrop" onMouseDown={()=>setOpen(false)}><div className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{editing?'Edit':'New'}</span><h2>{cfg.title.slice(0,-1)}</h2></div><button onClick={()=>setOpen(false)}>✕</button></div><div className="drawer-form">{cfg.fields.map(f=><label key={f.name}>{f.label}{f.type==='textarea'?<textarea rows={4} value={form[f.name]||''} onChange={e=>change(f.name,e.target.value)}/>:f.type==='checkbox'?<input type="checkbox" checked={!!form[f.name]} onChange={e=>change(f.name,e.target.checked)}/>:f.type==='select'?<select value={form[f.name]||''} onChange={e=>change(f.name,e.target.value)}><option value="">Select</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==='image'?<div className="upload-field"><input value={form[f.name]||''} placeholder="Image URL or upload below" onChange={e=>change(f.name,e.target.value)}/><input type="file" accept="image/*,.gif" onChange={e=>upload(f.name,e.target.files?.[0])}/>{uploading===f.name&&<small>Uploading…</small>}{form[f.name]&&<img src={form[f.name]} alt="Preview"/>}</div>:<input type={f.type==='number'?'number':f.type==='date'?'date':'text'} placeholder={f.placeholder} value={f.type==='json'&&typeof form[f.name]!=='string'?JSON.stringify(form[f.name]|| (f.placeholder?.startsWith('[')?[]:{})):form[f.name]||''} onChange={e=>change(f.name,f.type==='number'?Number(e.target.value):e.target.value)}/>}</label>)}<button className="btn btn-primary btn-wide" onClick={save}>Save changes</button>{resource==='projects'&&editing?.id&&<div className="gallery-admin"><h3>Project gallery</h3><p>Upload multiple project photos or GIFs. They appear on the public project detail page.</p><input type="file" accept="image/*,.gif" onChange={e=>addGallery(e.target.files?.[0])}/>{uploading==='gallery'&&<small>Uploading gallery image…</small>}<div className="gallery-admin-grid">{media.map(m=><div key={m.id}><img src={m.media_url} alt="Project gallery"/><button onClick={()=>removeMedia(m.id)}>Remove</button></div>)}</div></div>}</div></div></div>}</div>}
