import { Client, Product, Project, Service, SiteSettings } from './types';

export const defaultSettings: SiteSettings = {
  site_name: 'Green X Power Engineering',
  tagline: 'Powering the Future, Sustainably.',
  hero_title: 'Reliable Power. Smarter Energy. Stronger Infrastructure.',
  hero_subtitle: 'Integrated solar, generator, lift and electrical engineering solutions for homes, businesses and industries across Bangladesh.',
  phone: '01717202172', whatsapp: '01717202172', email: null,
  address: 'Spring Rahmat-e Tuba Complex, House-132 (3rd Floor), Block-A, Road-2, Section-12, Mirpur, Dhaka-1216, Bangladesh.',
  about_short: 'Engineering solutions built around reliability, safety and long-term support.',
  about_full: 'Green X Power Engineering supports clients from consultation and site survey through design, supply, installation, commissioning and maintenance. Our focus is practical engineering, dependable equipment and responsive after-sales service.',
  mission: 'Deliver safe, efficient and dependable engineering solutions tailored to each client while advancing sustainable energy use.',
  vision: 'Build a trusted Bangladesh engineering brand known for reliable power, modern infrastructure and long-term service.',
  years_experience: null, total_projects: null, total_clients: null
};

export const demoServices: Service[] = [
  { title:'Solar Energy', slug:'solar-energy', short_description:'Rooftop, hybrid and off-grid solar systems for commercial, industrial and residential use.', description:'End-to-end solar engineering—from site survey and load analysis to system design, equipment selection, installation, testing and O&M.', image_url:'/assets/solar.svg', features:['Rooftop solar','Hybrid & off-grid systems','Solar generator integration','Energy storage','Testing & commissioning','O&M support'], featured:true, published:true },
  { title:'Generator & Backup Power', slug:'generator-backup-power', short_description:'Reliable standby power and backup integration for business-critical operations.', description:'Generator sizing, supply, installation, ATS/synchronization, commissioning and preventive maintenance.', image_url:'/assets/generator.svg', features:['Diesel generator','ATS & synchronization','UPS/IPS integration','Load planning','Commissioning','Preventive maintenance'], featured:true, published:true },
  { title:'Lift & Elevator', slug:'lift-elevator', short_description:'Passenger, hospital, cargo and building lift solutions with maintenance support.', description:'Lift planning, supply, installation, modernization, testing and scheduled maintenance for residential and commercial buildings.', image_url:'/assets/lift.svg', features:['Passenger lift','Hospital lift','Cargo lift','Home lift','Modernization','AMC & maintenance'], featured:true, published:true },
  { title:'Electrical Engineering', slug:'electrical-engineering', short_description:'Power distribution, protection and electrical installation for modern facilities.', description:'Practical electrical design and field implementation covering distribution, protection, backup integration and system improvement.', image_url:'/assets/electrical.svg', features:['LV distribution','Panel & protection','Cabling','Earthing','Power quality','Testing'], featured:true, published:true },
  { title:'Lightning Protection', slug:'lightning-protection', short_description:'Lightning protection, earthing and safety systems for buildings and facilities.', description:'Site assessment, protection design, installation, earthing, testing and maintenance.', image_url:'/assets/lightning.svg', features:['Lightning protection','Earthing','Surge protection','Risk assessment','Testing','Maintenance'], featured:false, published:true },
  { title:'Maintenance & Support', slug:'maintenance-support', short_description:'Preventive maintenance, repair, AMC and technical support across Green X systems.', description:'Protect system uptime with planned inspections, service visits, emergency support and annual maintenance contracts.', image_url:'/assets/maintenance.svg', features:['Preventive maintenance','Corrective maintenance','AMC','Emergency support','Inspection reports','Spare planning'], featured:true, published:true }
];

export const demoProjects: Project[] = [
  { title:'Industrial Rooftop Solar — Portfolio Preview', slug:'industrial-rooftop-solar-preview', category:'Solar Energy', client_name:'Sample industrial facility', location:'Gazipur, Bangladesh', capacity:'250 kWp', completion_date:'2026-06-20', short_description:'A sample case-study layout for a commercial rooftop system designed around daytime load reduction.', description:'This is presentation data included to show how a completed Green X project will appear. Replace it from Admin with an actual Green X project before using it as a company claim.', cover_image_url:'/assets/solar-project.svg', services_provided:['Site survey','Design','Supply','Installation','Testing & commissioning'], technical_details:{System:'Grid-tied rooftop PV',Capacity:'250 kWp',Application:'Industrial daytime load'}, featured:true, published:true, demo:true },
  { title:'Commercial Standby Generator — Portfolio Preview', slug:'commercial-generator-preview', category:'Generator & Backup Power', client_name:'Sample commercial building', location:'Dhaka, Bangladesh', capacity:'250 kVA', completion_date:'2026-05-08', short_description:'A clean project presentation for standby generation, changeover and commissioning.', description:'Sample portfolio content. Replace with Green X project information from Admin.', cover_image_url:'/assets/generator-project.svg', services_provided:['Load assessment','Supply','Installation','ATS integration','Commissioning'], technical_details:{Capacity:'250 kVA',Application:'Commercial standby power',Scope:'Supply + installation'}, featured:true, published:true, demo:true },
  { title:'Passenger Lift Installation — Portfolio Preview', slug:'passenger-lift-preview', category:'Lift & Elevator', client_name:'Sample residential tower', location:'Dhaka, Bangladesh', capacity:'10 Persons', completion_date:'2026-04-18', short_description:'Example case study showing lift scope, capacity, project images and maintenance handover.', description:'Sample portfolio content. Replace with Green X project information from Admin.', cover_image_url:'/assets/lift-project.svg', services_provided:['Planning','Supply','Installation','Testing','Maintenance handover'], technical_details:{Type:'Passenger lift',Capacity:'10 persons',Application:'Residential tower'}, featured:true, published:true, demo:true },
  { title:'Lightning Protection & Earthing — Portfolio Preview', slug:'lightning-protection-preview', category:'Lightning Protection', client_name:'Sample industrial facility', location:'Chattogram, Bangladesh', capacity:'Facility-wide', completion_date:'2026-03-12', short_description:'Example presentation of a building protection and earthing improvement project.', description:'Sample portfolio content. Replace with Green X project information from Admin.', cover_image_url:'/assets/electrical-project.svg', services_provided:['Risk review','Design','Installation','Earth testing','Handover'], technical_details:{Scope:'Lightning + earthing',Application:'Industrial facility'}, featured:false, published:true, demo:true }
];

export const demoProducts: Product[] = [
  { name:'GX SolarBox 500', slug:'gx-solarbox-500', category:'Solar Generators', brand:'Green X Demo Range', short_description:'Compact 500W portable backup concept with LiFePO4 storage for essential loads.', description:'Sample product presentation demonstrating specifications, enquiry CTA and category navigation. Replace with the exact brands/models you supply.', image_url:'/assets/product-powerstation.svg', specifications:{RatedOutput:'500W',Battery:'512Wh LiFePO4',Charging:'AC + Solar',Use:'Home / field backup'}, featured:true, published:true, demo:true },
  { name:'GX SolarBox 1500', slug:'gx-solarbox-1500', category:'Solar Generators', brand:'Green X Demo Range', short_description:'Higher-capacity portable solar backup concept for office, home and field applications.', description:'Sample product. Add your real model and supplier data from Admin.', image_url:'/assets/product-powerstation.svg', specifications:{RatedOutput:'1500W',Battery:'1.5kWh LiFePO4',Output:'Pure sine wave',Charging:'AC + Solar'}, featured:true, published:true, demo:true },
  { name:'Mono PERC 550W PV Module', slug:'mono-perc-550w', category:'Solar Panels', brand:'Sample Tier-1 Module', short_description:'High-output module example for rooftop and commercial PV projects.', description:'Example catalog card. Replace brand, warranty and electrical data with your approved supply line.', image_url:'/assets/product-panel.svg', specifications:{Power:'550W',Cell:'Mono PERC',Application:'Rooftop / C&I',Warranty:'Configure from Admin'}, featured:true, published:true, demo:true },
  { name:'5kW Hybrid Solar Inverter', slug:'hybrid-inverter-5kw', category:'Inverters', brand:'Sample Hybrid Series', short_description:'Hybrid inverter concept with PV, battery and grid integration.', description:'Sample product layout.', image_url:'/assets/product-inverter.svg', specifications:{RatedPower:'5kW',Topology:'Hybrid',Battery:'48V / compatible storage',Monitoring:'Smart monitoring ready'}, featured:false, published:true, demo:true },
  { name:'5.12kWh LiFePO4 Battery', slug:'lifepo4-battery-512', category:'Battery & Storage', brand:'Sample Storage Series', short_description:'Long-life lithium storage concept for solar and backup applications.', description:'Sample product layout.', image_url:'/assets/product-battery.svg', specifications:{Energy:'5.12kWh',Chemistry:'LiFePO4',Application:'Solar / backup',Scalability:'Parallel-ready concept'}, featured:false, published:true, demo:true },
  { name:'Silent Diesel Generator 50kVA', slug:'silent-generator-50kva', category:'Generators', brand:'Sample Generator Range', short_description:'Silent-type standby generator concept for commercial power continuity.', description:'Sample product layout.', image_url:'/assets/generator.svg', specifications:{PrimePower:'Configure from Admin',Standby:'50 kVA class',Enclosure:'Silent canopy',Control:'Auto-start capable'}, featured:true, published:true, demo:true },
  { name:'GX-P10 Passenger Lift', slug:'gx-p10-passenger-lift', category:'Lift & Elevator', brand:'Green X Demo Range', short_description:'Modern passenger lift presentation for residential and commercial buildings.', description:'Sample lift product page.', image_url:'/assets/lift.svg', specifications:{Capacity:'10 persons',Drive:'VVVF concept',Doors:'Automatic',Service:'Installation + AMC'}, featured:true, published:true, demo:true },
  { name:'Online UPS 10kVA', slug:'online-ups-10kva', category:'UPS & Power Backup', brand:'Sample UPS Series', short_description:'Online double-conversion UPS concept for IT and critical equipment.', description:'Sample UPS product page.', image_url:'/assets/product-ups.svg', specifications:{Capacity:'10 kVA',Topology:'Online double conversion',Application:'IT / critical load',Battery:'External bank compatible'}, featured:false, published:true, demo:true }
];

export const demoClients: Client[] = [
  {name:'Industrial', published:true}, {name:'Commercial', published:true}, {name:'Residential', published:true}, {name:'Infrastructure', published:true}
];
