import type { Client, Product, Project, Service, SiteSettings } from './types';
import {
  PHOTO_BATTERY,
  PHOTO_DATACENTER,
  PHOTO_ELECTRICAL,
  PHOTO_ELECTRICAL_ALT,
  PHOTO_ELEVATOR,
  PHOTO_ELEVATOR_INTERIOR,
  PHOTO_ELEVATOR_PREMIUM,
  PHOTO_GENERATOR,
  PHOTO_GENERATOR_ALT,
  PHOTO_HERO_SOLAR,
  PHOTO_SERVER,
  PHOTO_SOLAR_BD,
  PHOTO_SOLAR_FACTORY,
  PHOTO_SOLAR_FIELD,
  PHOTO_SOLAR_ROOFTOP,
  PHOTO_SOLAR_TECH,
} from './visuals';

export const defaultSettings: SiteSettings = {
  site_name: 'Greenex Power Engineering',
  tagline: 'Sustainable & Innovative Engineering Solutions',
  hero_title: 'Sustainable & Innovative Engineering Solutions',
  hero_subtitle: 'Practical, future-ready power, renewable energy, lift and electrical engineering—from consultation and design to installation, commissioning and long-term support.',
  hero_image_url: PHOTO_HERO_SOLAR,
  logo_url: '/assets/greenex-logo.png',
  phone: '01717202172',
  whatsapp: '+8801736432848',
  email: null,
  address: 'Spring Rahmat-e Tuba Complex, House-132 (3rd Floor), Block-A, Road-2, Section-12, Mirpur, Dhaka-1216, Bangladesh.',
  facebook_url: null,
  linkedin_url: null,
  youtube_url: null,
  map_url: 'https://www.google.com/maps/search/?api=1&query=Mirpur%20Dhaka%201216%20Bangladesh',
  about_short: 'Sustainable engineering, practical innovation and dependable lifecycle support for power, solar, lift and electrical projects.',
  about_full: 'Greenex Power Engineering supports commercial, industrial, residential and institutional clients from early consultation and site survey through system design, equipment selection, supply, installation, testing, commissioning and maintenance. The approach is practical: understand the real load, operating risk, site constraints and lifecycle service requirement before selecting equipment.',
  mission: 'Deliver sustainable and innovative engineering solutions that are safe, efficient, maintainable and shaped around real client requirements.',
  vision: 'Build a trusted engineering brand in Bangladesh by combining sustainable technology, practical innovation and dependable long-term support.',
  years_experience: null,
  total_projects: null,
  total_clients: null,
};

export const demoServices: Service[] = [
  { title:'Solar Energy', slug:'solar-energy', short_description:'Rooftop, hybrid and off-grid solar designed around the site, load profile and operating target.', description:'Greenex supports solar projects from feasibility and site survey through sizing, equipment selection, structural/layout coordination, installation, testing, commissioning and maintenance.', icon_url:'/assets/solar.svg', image_url:PHOTO_SOLAR_FACTORY, features:['Industrial rooftop solar','Commercial solar PV','Hybrid & off-grid systems','Battery storage integration','Solar generator solutions','Testing, monitoring & O&M'], featured:true, published:true, display_order:1 },
  { title:'Generator & Backup Power', slug:'generator-backup-power', short_description:'Standby and prime-power systems sized for critical loads and dependable changeover.', description:'Generator engineering covers load assessment, equipment selection, ATS/changeover integration, installation, exhaust and fuel coordination, commissioning and preventive maintenance.', icon_url:'/assets/generator.svg', image_url:PHOTO_GENERATOR, features:['Diesel generator systems','Load & diversity assessment','ATS / AMF integration','Acoustic & ventilation planning','Testing & load commissioning','Preventive maintenance'], featured:true, published:true, display_order:2 },
  { title:'Lift & Elevator', slug:'lift-elevator', short_description:'Passenger, hospital, cargo and building lift solutions with installation and AMC support.', description:'Greenex coordinates lift planning, capacity selection, shaft/site requirements, equipment supply, installation, testing, handover, modernization and planned maintenance.', icon_url:'/assets/lift.svg', image_url:PHOTO_ELEVATOR_PREMIUM, features:['Passenger lift','Hospital / bed lift','Cargo lift','Home lift','Modernization & retrofit','AMC & maintenance'], featured:true, published:true, display_order:3 },
  { title:'Electrical Engineering', slug:'electrical-engineering', short_description:'Distribution, protection, panels and integration for facilities that depend on stable power.', description:'Electrical engineering services support LV distribution, panel systems, cabling, protection, earthing, backup integration, power-quality improvement and final testing.', icon_url:'/assets/electrical.svg', image_url:PHOTO_ELECTRICAL, features:['LV distribution','MDB / SDB panels','Cabling & containment','Protection coordination','Earthing & bonding','Testing & handover'], featured:true, published:true, display_order:4 },
  { title:'Lightning Protection', slug:'lightning-protection', short_description:'Lightning, surge and earthing solutions focused on people, equipment and facility protection.', description:'The scope can include risk review, air terminals, down conductors, earth electrode systems, surge protection devices, testing and maintenance planning.', icon_url:'/assets/lightning.svg', image_url:PHOTO_ELECTRICAL_ALT, features:['Lightning risk review','Air termination system','Down conductors','Earthing system','Surge protection','Earth resistance testing'], featured:false, published:true, display_order:5 },
  { title:'Maintenance & Support', slug:'maintenance-support', short_description:'Preventive and corrective engineering support to protect uptime and equipment life.', description:'Maintenance programs can combine inspections, servicing, fault response, performance checks, reporting, spare planning and annual maintenance contracts across Greenex systems.', icon_url:'/assets/maintenance.svg', image_url:PHOTO_SOLAR_TECH, features:['Preventive maintenance','Corrective maintenance','AMC programs','Emergency response','Inspection & service reports','Spare-part planning'], featured:true, published:true, display_order:6 },
];

export const demoProjects: Project[] = [
  {
    title:'Industrial Rooftop Solar | 250 kWp Reference Scope', slug:'industrial-rooftop-solar-250kwp', category:'Solar Energy', client_name:'Industrial manufacturing facility', location:'Gazipur, Bangladesh', capacity:'250 kWp', completion_date:'2026-07-18',
    short_description:'A representative industrial rooftop PV scope built around daytime demand, maintainable access and safe grid integration.',
    description:'This reference project demonstrates how Greenex would structure an industrial rooftop solar assignment: site survey, load-profile review, roof zoning, string/inverter planning, protection, monitoring, installation sequencing, testing and O&M access. Final energy yield and commercial savings always depend on verified site data.',
    cover_image_url:PHOTO_SOLAR_ROOFTOP, services_provided:['Energy & load review','Rooftop survey','PV layout & sizing','Inverter/protection selection','Installation supervision','Testing & commissioning','O&M planning'],
    technical_details:{'PV capacity':'250 kWp','Module class':'550 W mono','Estimated module count':'~455 modules','System type':'Grid-tied / hybrid-ready','Monitoring':'Web / app capable','Primary use':'Daytime industrial load reduction'}, featured:true, published:true, demo:true, display_order:1,
  },
  {
    title:'Factory Solar Expansion | 500 kWp Reference Scope', slug:'factory-solar-expansion-500kwp', category:'Solar Energy', client_name:'RMG / textile application', location:'Narayanganj, Bangladesh', capacity:'500 kWp', completion_date:'2026-06-30',
    short_description:'A larger rooftop configuration focused on staged installation, generation monitoring and future expansion.',
    description:'Representative engineering for a high-consumption factory where roof zones, operating hours, transformer capacity and phased construction influence the solar design. The scope demonstrates expansion-ready architecture and maintainability rather than a claimed Greenex client installation.',
    cover_image_url:PHOTO_SOLAR_FACTORY, services_provided:['Feasibility study','Roof-zone planning','DC/AC design','Cable & protection coordination','Monitoring architecture','Commissioning plan'],
    technical_details:{'PV capacity':'500 kWp','System topology':'Multi-inverter','Use case':'Industrial self-consumption','Expansion':'Future-ready zoning','Safety':'DC isolation + SPD strategy','Maintenance':'Planned access corridors'}, featured:true, published:true, demo:true, display_order:2,
  },
  {
    title:'Commercial Standby Generator | 250 kVA Reference Scope', slug:'commercial-standby-power-250kva', category:'Generator & Backup Power', client_name:'Commercial building', location:'Dhaka, Bangladesh', capacity:'250 kVA', completion_date:'2026-05-22',
    short_description:'Standby-generation planning with ATS integration, essential-load continuity and maintainable service access.',
    description:'A representative standby-power assignment showing the engineering decisions around load grouping, generator reserve, ATS/AMF operation, cable sizing, ventilation, exhaust, fuel, acoustic considerations and commissioning.',
    cover_image_url:PHOTO_GENERATOR, services_provided:['Load assessment','Generator sizing','ATS / AMF integration','Electrical connection','Ventilation/exhaust coordination','Commissioning'],
    technical_details:{'Generator class':'250 kVA','Duty':'Emergency standby','Changeover':'Automatic','Fuel':'Diesel','Critical loads':'Lift, fire, lighting, ICT','Service plan':'Preventive maintenance ready'}, featured:true, published:true, demo:true, display_order:3,
  },
  {
    title:'Prime & Emergency Power | 80 kVA Reference Scope', slug:'prime-emergency-power-80kva', category:'Generator & Backup Power', client_name:'Institutional facility', location:'Dhaka, Bangladesh', capacity:'80 kVA', completion_date:'2026-04-15',
    short_description:'Compact generator architecture for essential loads with automatic transfer and service-friendly placement.',
    description:'A reference application for facilities needing dependable emergency generation without oversizing. The project profile demonstrates load prioritization, ATS logic, generator placement and maintenance clearances.',
    cover_image_url:PHOTO_GENERATOR_ALT, services_provided:['Essential-load study','Equipment selection','ATS coordination','Cable route planning','Startup & testing'],
    technical_details:{'Generator class':'80 kVA','Application':'Essential backup','Control':'Auto start / stop','Transfer':'ATS','Noise strategy':'Canopy / placement dependent','Testing':'Functional + load verification'}, featured:false, published:true, demo:true, display_order:4,
  },
  {
    title:'Passenger Lift | 10 Person Reference Scope', slug:'passenger-lift-10-person', category:'Lift & Elevator', client_name:'Residential / commercial building', location:'Dhaka, Bangladesh', capacity:'10 Persons', completion_date:'2026-03-12',
    short_description:'Passenger-lift planning covering capacity, shaft coordination, VVVF operation, safety and lifecycle maintenance.',
    description:'This representative lift scope shows the information Greenex reviews before equipment selection: building height, stops, passenger demand, shaft size, machine-room strategy, power availability, finishes and maintenance access.',
    cover_image_url:PHOTO_ELEVATOR_PREMIUM, services_provided:['Site & shaft review','Capacity selection','Equipment supply','Installation','Testing & handover','AMC planning'],
    technical_details:{'Capacity':'10 persons / ~800 kg','Drive':'VVVF','Door':'Automatic center opening','Stops':'Project dependent','Power':'3-phase supply','Service':'AMC ready'}, featured:true, published:true, demo:true, display_order:5,
  },
  {
    title:'Hospital Lift | Bed Lift Reference Scope', slug:'hospital-bed-lift-reference', category:'Lift & Elevator', client_name:'Healthcare facility', location:'Dhaka, Bangladesh', capacity:'Bed Lift', completion_date:'2026-02-25',
    short_description:'Healthcare-focused lift planning prioritizing cabin usability, smooth travel and reliable maintenance support.',
    description:'A representative hospital/bed-lift application with attention to cabin dimensions, door opening, traffic demand, backup power, hygiene-friendly finishes and maintenance response.',
    cover_image_url:PHOTO_ELEVATOR, services_provided:['Traffic/use review','Cabin planning','Power coordination','Installation','Testing','Maintenance planning'],
    technical_details:{'Lift type':'Hospital / bed lift','Capacity':'Project selected','Door':'Wide automatic opening','Backup':'Generator compatible','Control':'VVVF','Priority':'Smooth & reliable operation'}, featured:false, published:true, demo:true, display_order:6,
  },
  {
    title:'LV Distribution & Control Upgrade | Reference Scope', slug:'electrical-distribution-control-upgrade', category:'Electrical Engineering', client_name:'Industrial production facility', location:'Gazipur, Bangladesh', capacity:'Custom Scope', completion_date:'2026-01-28',
    short_description:'Distribution and control-panel improvement focused on protection, maintainability and future load growth.',
    description:'A representative LV engineering package covering site assessment, single-line review, panel architecture, protective devices, cabling, labeling, testing and handover documentation.',
    cover_image_url:PHOTO_ELECTRICAL, services_provided:['Site assessment','SLD review','Panel design','Protection review','Installation support','Testing & documentation'],
    technical_details:{'System':'LV distribution','Main scope':'MDB / SDB / controls','Protection':'MCCB / MCB / SPD as required','Documentation':'SLD + schedules','Testing':'Insulation / functional checks','Growth':'Spare-capacity planning'}, featured:false, published:true, demo:true, display_order:7,
  },
  {
    title:'Earthing & Lightning Protection | Reference Scope', slug:'earthing-lightning-protection-reference', category:'Lightning Protection', client_name:'Commercial / industrial facility', location:'Bangladesh', capacity:'Site Specific', completion_date:'2025-12-20',
    short_description:'A site-specific protection concept covering lightning interception, down conductors, earthing and surge protection.',
    description:'Representative protection engineering that starts from structure/site risk and coordinates the external lightning-protection system with internal surge protection and verified earthing performance.',
    cover_image_url:PHOTO_ELECTRICAL_ALT, services_provided:['Risk/site review','Air termination planning','Down conductor routing','Earth electrode system','SPD coordination','Earth resistance testing'],
    technical_details:{'Protection':'External + internal','Earthing':'Site specific','SPD':'Panel/application dependent','Test':'Earth resistance','Documentation':'Test records','Maintenance':'Periodic inspection'}, featured:false, published:true, demo:true, display_order:8,
  },
];

export const demoProducts: Product[] = [
  { name:'Portable Solar Power Station | 600 W', slug:'portable-solar-power-station-600w', category:'Solar Generators', brand:'Greenex Engineering Selection', short_description:'Portable LFP-based backup for field teams, small offices, home essentials and emergency charging.', description:'A representative 600 W portable solar-generator class combining inverter output, LiFePO4 storage and AC/solar charging. Final model selection depends on load type, runtime and charging requirements.', image_url:PHOTO_SOLAR_BD, brochure_url:null, specifications:{'AC output':'600 W class','Battery chemistry':'LiFePO4','Usable energy':'Model dependent','Solar input':'MPPT capable','Outputs':'AC / DC / USB','Application':'Portable backup'}, featured:true, published:true, demo:true, display_order:1 },
  { name:'Portable Solar Power Station | 2 kW', slug:'portable-solar-power-station-2kw', category:'Solar Generators', brand:'Greenex Engineering Selection', short_description:'Higher-capacity portable backup for offices, field operations and selected appliance loads.', description:'Representative 2 kW portable power-station class with solar charging and LFP battery technology for applications requiring higher inverter capacity and longer runtime.', image_url:PHOTO_SOLAR_TECH, brochure_url:null, specifications:{'AC output':'2,000 W class','Battery':'LFP configuration','Charging':'AC + solar','Expansion':'Model dependent','Monitoring':'Model dependent','Application':'Office / field / emergency'}, featured:false, published:true, demo:true, display_order:2 },
  { name:'Mono PV Module | 550 W', slug:'mono-pv-module-550w', category:'Solar Panels', brand:'Project Equipment Class', short_description:'High-output monocrystalline PV module class for commercial and industrial rooftop projects.', description:'Representative 550 W module class used for planning modern rooftop arrays. Final module is selected around efficiency, dimensions, certification, warranty, availability and project design.', image_url:PHOTO_SOLAR_ROOFTOP, brochure_url:null, specifications:{'Rated power':'550 W class','Cell technology':'Mono crystalline','Module efficiency':'Model dependent','Connector':'MC4-type','Application':'C&I rooftop / utility','Warranty':'Manufacturer dependent'}, featured:true, published:true, demo:true, display_order:3 },
  { name:'N-Type PV Module | 585 W', slug:'n-type-pv-module-585w', category:'Solar Panels', brand:'Project Equipment Class', short_description:'N-type high-power PV module class for projects targeting higher watts per module and optimized roof use.', description:'Representative N-type module class for commercial design studies. Final selection considers module dimensions, string voltage, warranty, bankability and local availability.', image_url:PHOTO_SOLAR_FACTORY, brochure_url:null, specifications:{'Rated power':'585 W class','Technology':'N-type mono','Application':'Commercial / industrial','Design':'Half-cut / bifacial options','Warranty':'Model dependent','Selection':'Project engineered'}, featured:false, published:true, demo:true, display_order:4 },
  { name:'Hybrid Solar Inverter | 10 kW', slug:'hybrid-solar-inverter-10kw', category:'Inverters', brand:'Project Equipment Class', short_description:'Three-phase hybrid inverter class for solar, battery and grid interaction.', description:'Representative hybrid inverter class for sites requiring PV generation, storage integration and backup operating modes. Final topology depends on grid, load and battery architecture.', image_url:PHOTO_ELECTRICAL_ALT, brochure_url:null, specifications:{'Rated output':'10 kW class','Topology':'Hybrid','PV MPPT':'Multi-MPPT dependent','Battery':'HV/LV model dependent','Monitoring':'Web / app options','Application':'Commercial / premium residential'}, featured:true, published:true, demo:true, display_order:5 },
  { name:'On-Grid String Inverter | 50 kW', slug:'on-grid-string-inverter-50kw', category:'Inverters', brand:'Project Equipment Class', short_description:'Commercial string-inverter class for rooftop PV arrays with multi-MPPT architecture.', description:'Representative C&I inverter category used for larger rooftop system design. Final equipment is coordinated with string voltage, protection, monitoring and grid requirements.', image_url:PHOTO_DATACENTER, brochure_url:null, specifications:{'Rated output':'50 kW class','Phase':'3-phase','Topology':'On-grid string','MPPT':'Multi-MPPT','Monitoring':'Plant monitoring capable','Application':'C&I rooftop solar'}, featured:false, published:true, demo:true, display_order:6 },
  { name:'LiFePO4 Energy Storage | 5.12 kWh', slug:'lifepo4-energy-storage-5-12kwh', category:'Battery & Storage', brand:'Greenex Engineering Selection', short_description:'Modular LFP storage for solar backup, time-shifting and critical-load continuity.', description:'Representative 5.12 kWh LFP module class. Battery quantity, usable depth of discharge and inverter compatibility are selected around runtime and cycle requirements.', image_url:PHOTO_BATTERY, brochure_url:null, specifications:{'Nominal energy':'5.12 kWh class','Chemistry':'LiFePO4','Cycle life':'Model dependent','Communication':'CAN / RS485 options','Expansion':'Parallel modules','Application':'Solar / backup'}, featured:true, published:true, demo:true, display_order:7 },
  { name:'Rack Battery Storage | 20 kWh', slug:'rack-battery-storage-20kwh', category:'Battery & Storage', brand:'Project Equipment Class', short_description:'Scalable rack-style storage concept for commercial backup and hybrid solar projects.', description:'Representative commercial battery-bank architecture combining multiple LFP modules with compatible BMS and inverter systems.', image_url:PHOTO_SERVER, brochure_url:null, specifications:{'Energy':'20 kWh class','Chemistry':'LiFePO4','Format':'Rack / cabinet','BMS':'Integrated','Expansion':'Scalable','Application':'Commercial hybrid / UPS'}, featured:false, published:true, demo:true, display_order:8 },
  { name:'Silent Diesel Generator | 50 kVA', slug:'silent-diesel-generator-50kva', category:'Generators', brand:'Project Equipment Class', short_description:'Compact silent-canopy generator class for commercial and building standby applications.', description:'Representative 50 kVA generator class used during early load planning. Final selection considers duty, ambient conditions, fuel system, acoustic limit, alternator and control requirements.', image_url:PHOTO_GENERATOR, brochure_url:null, specifications:{'Standby rating':'50 kVA class','Fuel':'Diesel','Enclosure':'Silent canopy','Controller':'Auto-start capable','ATS':'Optional / integrated project','Application':'Building / commercial backup'}, featured:true, published:true, demo:true, display_order:9 },
  { name:'Industrial Diesel Generator | 250 kVA', slug:'industrial-diesel-generator-250kva', category:'Generators', brand:'Project Equipment Class', short_description:'Industrial standby-generator class for higher critical-load and facility continuity requirements.', description:'Representative 250 kVA generator package. Site engineering coordinates ventilation, exhaust, fuel, earthing, ATS, cabling and maintenance access.', image_url:PHOTO_GENERATOR_ALT, brochure_url:null, specifications:{'Standby rating':'250 kVA class','Duty':'Standby / prime model dependent','Control':'AMF capable','Cooling':'Radiator cooled','Integration':'ATS + distribution','Application':'Industrial / large commercial'}, featured:false, published:true, demo:true, display_order:10 },
  { name:'Passenger Lift | 10 Person', slug:'passenger-lift-p10', category:'Lift & Elevator', brand:'Greenex Engineering Selection', short_description:'Passenger-lift class for apartment, office and mixed-use building applications.', description:'Representative lift specification used to illustrate capacity and drive selection. Final model depends on travel, stops, shaft dimensions, traffic, finishes and local project constraints.', image_url:PHOTO_ELEVATOR_INTERIOR, brochure_url:null, specifications:{'Capacity':'10 persons / ~800 kg','Drive':'VVVF','Door':'Automatic','Speed':'Project dependent','Stops':'Project dependent','Service':'Installation + AMC'}, featured:true, published:true, demo:true, display_order:11 },
  { name:'Hospital / Bed Lift', slug:'hospital-bed-lift', category:'Lift & Elevator', brand:'Greenex Engineering Selection', short_description:'Healthcare-oriented lift class with larger cabin and door planning for patient movement.', description:'Representative hospital/bed-lift product class. Cabin dimensions, capacity, openings, finishes and backup integration are configured around the facility.', image_url:PHOTO_ELEVATOR_PREMIUM, brochure_url:null, specifications:{'Type':'Hospital / bed lift','Capacity':'Project selected','Door':'Wide automatic','Drive':'VVVF','Backup':'Generator compatible','Application':'Hospital / clinic'}, featured:false, published:true, demo:true, display_order:12 },
  { name:'Online UPS | 10 kVA', slug:'online-ups-10kva', category:'UPS & Power Backup', brand:'Project Equipment Class', short_description:'Double-conversion UPS class for ICT, control systems and other sensitive critical loads.', description:'Representative 10 kVA online UPS category. Runtime, battery bank, redundancy and bypass are configured around load criticality and available space.', image_url:PHOTO_DATACENTER, brochure_url:null, specifications:{'Capacity':'10 kVA','Topology':'Online double conversion','Phase':'Model dependent','Bypass':'Static / maintenance options','Battery':'External bank compatible','Application':'ICT / controls / critical load'}, featured:true, published:true, demo:true, display_order:13 },
  { name:'Online UPS | 30 kVA', slug:'online-ups-30kva', category:'UPS & Power Backup', brand:'Project Equipment Class', short_description:'Three-phase UPS class for larger ICT rooms, critical equipment and facility controls.', description:'Representative 30 kVA UPS class for applications requiring clean uninterrupted power and engineered battery runtime.', image_url:PHOTO_SERVER, brochure_url:null, specifications:{'Capacity':'30 kVA class','Topology':'Online double conversion','Input':'3-phase class','Output':'3-phase class','Battery':'External cabinet / rack','Application':'Data / medical / process control'}, featured:false, published:true, demo:true, display_order:14 },
];

export const demoClients: Client[] = [
  {name:'RMG & Textile Facilities', published:true, display_order:1},
  {name:'Commercial Buildings', published:true, display_order:2},
  {name:'Residential Developments', published:true, display_order:3},
  {name:'Healthcare & Institutions', published:true, display_order:4},
  {name:'ICT & Critical Facilities', published:true, display_order:5},
  {name:'Infrastructure & Utilities', published:true, display_order:6},
];
